filter_settings.filter_image_resize:
  type: filter
  label: 'Image Resize Filter Settings'
  mapping:
    image_locations:
      type: sequence
      label: 'Image locations'
      sequence:
        type: string
        label: 'Image location'
    link_class:
      type: string
      label: 'Link class'
    link_rel:
      type: string
      label: 'Rel attribute'

