filter_settings.filter_image_resize:
  type: filter
  label: 'Image Resize Filter Settings'
  mapping:
    image_locations:
      type: sequence
      label: 'Image locations'
      sequence:
        type: string
        label: 'Image location'
